命令稿啟動於 2016年03月 1日 下午 04:45:35
]0;~
[32mMMLab@MMLab-P45V [33m~[0m
$ git config -l[C[Cscript lab1.script[C[C[5Pgit config -l-global user.email "ching93011@gmail.com"[C[C[C[C[C[C[C[C[C[C[C[C[C[Cl[K-global user.email "ching93011@gmail.com"[10Pname "ShuoHsuanLi"[C[C[C[C[C[C[C[C[C[C[C[C[C[9P[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[10Pfind /usr -name iostream[C[Cgit clone https://github.com/csiebear/lab1.git[C[C[C[C[C[C[Config -l[K[C[C[3Pwhoami;pwd[C[Cfind /usr -name iostream[C[C[14Pwhoami;pwd
MMLab
/home/MMLab
]0;~
[32mMMLab@MMLab-P45V [33m~[0m
$ whoami;pwd[C[Cgit config -l[C[Cscript lab1.script[C[C[5Pgit config -l
user.name=ShuoHsuanLi
user.email=ching93011@gmail.com
]0;~
[32mMMLab@MMLab-P45V [33m~[0m
$ git config -l[C[C[3Pwhoami;pwd[C[Cgit config -l[C[Cscript lab1.script[C[C[5Pgit config -l-global user.email "ching93011@gmail.com"[10Pname "ShuoHsuanLi"email "ching93011@gmail.com"[C[C[C[C[C[C[C[C[C[C[C[C[C[Cl[K[C[Cscript lab1.script[C[C[5Pgit config -l[C[C[3Pwhoami;pwd[C[Cgit config -l[C[C[Kgit config -l[C[C[3Pwhoami;pwd[C[Cgit config -l[C[Cscript lab1.script[C[C[5Pgit config -l-global user.email "ching93011@gmail.com"[10Pname "ShuoHsuanLi"[C[C[C[C[C[C[C[C[C[C[C[C[C[9P[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[10Pfind /usr -name iostream[C[Cgit clone https://github.com/csiebear/lab1.git[C[C[C[C[C[C[Config -l[Klone https://github.com/csiebear/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;~
[32mMMLab@MMLab-P45V [33m~[0m
$ git clone https://github.com/csiebear/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 3[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
Checking connectivity... done.
]0;~
[32mMMLab@MMLab-P45V [33m~[0m
$ exit

命令稿已於 2016年03月 1日 下午 04:47:12
 完成