Script started on 2016年03月01日 (週二) 23時45分40秒
]0;F74004101@2015cpp: ~F74004101@2015cpp:~$ whoami;pwd
F74004101
/home/F74004101
]0;F74004101@2015cpp: ~F74004101@2015cpp:~$ git config -l
user.name=ShuoHsuanLi
user.email=ching93011@gmail.com
]0;F74004101@2015cpp: ~F74004101@2015cpp:~$ git clone h[Khttps://github.com/csiebear/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 14, done.[K
remote: Compressing objects:  10% (1/10)   [Kremote: Compressing objects:  20% (2/10)   [Kremote: Compressing objects:  30% (3/10)   [Kremote: Compressing objects:  40% (4/10)   [Kremote: Compressing objects:  50% (5/10)   [Kremote: Compressing objects:  60% (6/10)   [Kremote: Compressing objects:  70% (7/10)   [Kremote: Compressing objects:  80% (8/10)   [Kremote: Compressing objects:  90% (9/10)   [Kremote: Compressing objects: 100% (10/10)   [Kremote: Compressing objects: 100% (10/10), done.[K
remote: Total 14 (delta 2), reused 0 (delta 0), pack-reused 3[K
Unpacking objects:   7% (1/14)   Unpacking objects:  14% (2/14)   Unpacking objects:  21% (3/14)   Unpacking objects:  28% (4/14)   Unpacking objects:  35% (5/14)   Unpacking objects:  42% (6/14)   Unpacking objects:  50% (7/14)   Unpacking objects:  57% (8/14)   Unpacking objects:  64% (9/14)   Unpacking objects:  71% (10/14)   Unpacking objects:  78% (11/14)   Unpacking objects:  85% (12/14)   Unpacking objects:  92% (13/14)   Unpacking objects: 100% (14/14)   Unpacking objects: 100% (14/14), done.
]0;F74004101@2015cpp: ~F74004101@2015cpp:~$ exit

Script done on 2016年03月01日 (週二) 23時46分46秒
