Script started on 2016年03月01日 (週二) 23時57分02秒
]0;F74004101@2015cpp: ~/lab1F74004101@2015cpp:~/lab1$ git clone https://github.com/csiebear/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Config -l[K[3Pwhoami;pwd[6Pexitwhoami;pwdgit config -llone https://github.com/csiebear/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Kg==[K[K++ -o lab1 lab1.cpp
]0;F74004101@2015cpp: ~/lab1F74004101@2015cpp:~/lab1$ ./lab1
input n 
22
22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1 
]0;F74004101@2015cpp: ~/lab1F74004101@2015cpp:~/lab1$ exit

Script done on 2016年03月01日 (週二) 23時57分42秒
